services:
  bot:
    image: ghcr.io/adrianvillanueva997/telegrambot-reminders:latest@sha256:b67e40177c3a6b3d0e77ffa2d77e67fde0fabf15f0c40ff6f9cb2b7ae6f9f72e
    networks:
      - otlp
    container_name: telegrambot_reminders
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
networks:
  otlp:
    external: true
